In [1]:
import pandas as pd
import numpy as np

### 一、基础创建与查看

1. 导入 pandas，用字典创建 DataFrame：

   name: Tom, Jerry, Mike

   score: 85, 92, 78

   gender: 男，女，男

   

2. 查看上述 DataFrame 的前 1 行、形状、列名、数据类型。

   

3. 用列表创建 DataFrame：

   data = [[1, "A"], [2, "B"], [3, "C"]]

   列名设为 id、tag

In [29]:
# 1. 字典创建DataFrame
data_dict = {"name": ["Tom", "Jerry", "Mike"], "score": [85, 92, 78], "gender": ["男", "女", "男"]}
df = pd.DataFrame(data_dict)
df

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [30]:
# 2. 查看前1行
df.head(1)

  name  score gender
0  Tom     85      男

In [31]:
# 查看形状
df.shape

(3, 3)

In [32]:
# 查看列名
df.columns.tolist()

['name', 'score', 'gender']

In [33]:
# 查看数据类型
df.dtypes

name      object
score      int64
gender    object
dtype: object

In [34]:
# 3. 列表创建DataFrame
data_list = [[1, "A"], [2, "B"], [3, "C"]]
df_list = pd.DataFrame(data_list, columns=["id", "tag"])
df_list

   id tag
0   1   A
1   2   B
2   3   C

### 二、列与行操作

1. 选取 score 和 gender 两列。

   

2. 选取索引 0、2 的行。

   

3. 筛选 score>80 的行。

   

4. 新增一列 grade：score≥90 为优秀，否则为良好。

   

5. 删除 gender 列。

In [8]:
# 1. 选取score和gender两列
df[["score", "gender"]]

   score gender
0     85      男
1     92      女
2     78      男

In [9]:
# 2. 选取索引0、2的行
df.iloc[[0, 2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

In [10]:
# 3. 筛选score>80的行
df[df["score"] > 80]

    name  score gender
0    Tom     85      男
1  Jerry     92      女

In [11]:
# 4. 新增grade列
df["grade"] = np.where(df["score"] >= 90, "优秀", "良好")
df

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

In [12]:
# 5. 删除gender列
df.drop("gender", axis=1)

    name  score grade
0    Tom     85    良好
1  Jerry     92    优秀
2   Mike     78    良好

### 三、缺失值

1. 创建含缺失值的 DataFrame：

   data = {"x":[1, None, 3], "y":[None, 5, 6]}

   检测缺失值并统计每列缺失数量。

   

2. 用 0 填充缺失值；删除含缺失值的行。

In [13]:
# 1. 创建含缺失值的DataFrame
data_missing = {"x": [1, None, 3], "y": [None, 5, 6]}
df_missing = pd.DataFrame(data_missing)
df_missing

     x    y
0  1.0  NaN
1  NaN  5.0
2  3.0  6.0

In [14]:
# 检测缺失值
df_missing.isnull()

       x      y
0  False   True
1   True  False
2  False  False

In [15]:
# 统计每列缺失数量
df_missing.isnull().sum()

x    1
y    1
dtype: int64

In [16]:
# 2. 用0填充缺失值
df_missing.fillna(0)

     x    y
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

In [17]:
# 删除含缺失值的行
df_missing.dropna()

     x    y
2  3.0  6.0

### 四、分组聚合

1. 按 gender 分组，求 score 的均值和最大值。

   

2. 按 gender 分组，统计每组人数。

In [18]:
# 1. 按gender分组，求score的均值和最大值
df.groupby("gender")["score"].agg(["mean", "max"])

        mean  max
gender
女       92.0   92
男       81.5   85

In [19]:
# 2. 按gender分组统计人数
df.groupby("gender").size()

gender
女    1
男    2
dtype: int64

### 五、排序与去重

1. 按 score 升序排序。

   

2. 给 DataFrame 添加一行重复数据（如 Tom,85, 男），去重。

In [20]:
# 1. 按score升序排序
df.sort_values("score")

    name  score gender grade
2   Mike     78      男    良好
0    Tom     85      男    良好
1  Jerry     92      女    优秀

In [21]:
# 2. 添加重复数据
df_dup = pd.concat([df, pd.DataFrame([["Tom", 85, "男", "良好"]], columns=df.columns)], ignore_index=True)
df_dup

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好
3    Tom     85      男    良好

In [22]:
# 去重
df_dup.drop_duplicates()

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

### 六、合并与拼接

1. 横向合并：

   df1 = pd.DataFrame ({"id":[1,2], "name":["X","Y"]})

   df2 = pd.DataFrame ({"id":[1,2], "age":[20,30]})

   按 id 合并。

   

2. 纵向拼接：

   df_a = pd.DataFrame ({"val":[1,2]})

   df_b = pd.DataFrame ({"val":[3,4]})

   拼接后重置索引。

In [23]:
# 1. 按id横向合并
df1 = pd.DataFrame({"id": [1, 2], "name": ["X", "Y"]})
df2 = pd.DataFrame({"id": [1, 2], "age": [20, 30]})
pd.merge(df1, df2, on="id")

   id name  age
0   1    X   20
1   2    Y   30

In [24]:
# 2. 纵向拼接并重置索引
df_a = pd.DataFrame({"val": [1, 2]})
df_b = pd.DataFrame({"val": [3, 4]})
pd.concat([df_a, df_b], ignore_index=True)

   val
0    1
1    2
2    3
3    4

### 七、时间处理

1. 创建时间列：["2025-01-01","2025-01-02","2025-01-03"]，转为 datetime 格式。

   

2. 提取时间列的月份、星期。

In [25]:
# 1. 转为datetime格式
dates = ["2025-01-01", "2025-01-02", "2025-01-03"]
df_time = pd.DataFrame({"date": pd.to_datetime(dates)})
df_time

        date
0 2025-01-01
1 2025-01-02
2 2025-01-03

In [26]:
# 2. 提取月份、星期
df_time["month"] = df_time["date"].dt.month
df_time["weekday"] = df_time["date"].dt.weekday
df_time

        date  month  weekday
0 2025-01-01      1        2
1 2025-01-02      1        3
2 2025-01-03      1        4

### 八、高级操作

1. 对 score 列做标准化（(值 - 均值)/ 标准差）。

   

2. 用透视表：行是 gender，值是 score，聚合函数为中位数。

In [27]:
# 1. score列标准化
df["score_std"] = (df["score"] - df["score"].mean()) / df["score"].std()
df[["name", "score", "score_std"]]

    name  score  score_std
0    Tom     85        0.0
1  Jerry     92        1.0
2   Mike     78       -1.0

In [28]:
# 2. 透视表
pd.pivot_table(df, index="gender", values="score", aggfunc="median")

        score
gender
女        92.0
男        81.5